<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-JCSH58D" failures="1" tests="2" name="Data driven Test" time="22.668" errors="0" timestamp="2024-11-15T11:27:54 IST">
  <testcase classname="test.TC_002_LoginTest" name="loginTest" time="2.264"/>
  <testcase classname="test.TC_002_LoginTest" name="loginTest" time="1.758">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Login was successful. Please correct the errors and try again.] but found [Login was unsuccessful. Please correct the errors and try again.]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Login was successful. Please correct the errors and try again.] but found [Login was unsuccessful. Please correct the errors and try again.]
at pages.HomePage.validateLogin(HomePage.java:50)
at test.TC_002_LoginTest.loginTest(TC_002_LoginTest.java:33)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- loginTest -->
</testsuite> <!-- Data driven Test -->
