<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="4" hostname="DESKTOP-JCSH58D" failures="1" tests="4" name="Edge Test" time="45.687" errors="0" timestamp="2024-11-15T11:29:16 IST">
  <testcase classname="test.TC_001_RegisterTest" name="registerTest" time="2.867"/>
  <testcase classname="test.TC_002_LoginTest" name="loginTest" time="2.24"/>
  <testcase classname="test.TC_002_LoginTest" name="loginTest" time="1.859">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Login was successful. Please correct the errors and try again.] but found [Login was unsuccessful. Please correct the errors and try again.]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Login was successful. Please correct the errors and try again.] but found [Login was unsuccessful. Please correct the errors and try again.]
at pages.HomePage.validateLogin(HomePage.java:50)
at test.TC_002_LoginTest.loginTest(TC_002_LoginTest.java:33)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- loginTest -->
  <testcase classname="test.TC_003_InvalidLoginTest" name="invalidLogin" time="1.774"/>
  <testcase classname="base.ProjectSepcificationMethods" name="@BeforeSuite reportInitilization" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite reportInitilization -->
  <testcase classname="base.ProjectSepcificationMethods" name="@AfterSuite reportClose" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite reportClose -->
  <testcase classname="base.ProjectSepcificationMethods" name="@BeforeSuite reportInitilization" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite reportInitilization -->
  <testcase classname="base.ProjectSepcificationMethods" name="@AfterSuite reportClose" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite reportClose -->
</testsuite> <!-- Edge Test -->
